# Generated by Django 5.1.4 on 2026-06-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_app', '0002_groups_and_tasks'),
        ('workflow_app', '0002_inboxmessage'),
    ]

    operations = [
    ]
