# Generated by Django 5.1.4 on 2026-05-18 05:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
import workflow_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('financial', 'Financial Approvals'), ('employee_benefits', 'Employee Benefits'), ('operational', 'Operational Approvals'), ('administrative', 'Administrative')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('min_approvers', models.PositiveIntegerField(default=2)),
                ('max_approvers', models.PositiveIntegerField(default=50)),
                ('min_required_from_division', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Approval Categories',
                'db_table': 'workflow_categories',
                'ordering': ['group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('head_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workflow_divisions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('initiator', 'Initiator'), ('approver', 'Approver'), ('chief_manager', 'Chief Manager'), ('sub_manager', 'Sub Manager'), ('manager_operations', 'Manager Operations'), ('division_head', 'Division Head'), ('branch_manager', 'Branch Manager'), ('md', 'Managing Director'), ('admin', 'Administrator'), ('maker', 'Maker'), ('checker', 'Checker')], default='initiator', max_length=30)),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to=workflow_app.models.signature_upload_path)),
                ('is_available_for_approval', models.BooleanField(default=True)),
                ('on_leave', models.BooleanField(default=False)),
                ('delegate_until', models.DateTimeField(blank=True, null=True)),
                ('delegation_authority', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('delegate_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_from', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'workflow_users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('date', models.DateField(auto_now_add=True)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('in_progress', 'In Progress'), ('approved', 'Fully Approved'), ('rejected', 'Rejected'), ('returned', 'Returned for Modification'), ('payment_pending', 'Payment Pending'), ('payment_released', 'Payment Released')], default='draft', max_length=20)),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('total_steps', models.PositiveIntegerField(default=1)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('attachments_note', models.TextField(blank=True)),
                ('attachment_file', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('pdf_mode', models.CharField(choices=[('system', 'System Generated'), ('manual', 'Manual Signature Print'), ('digital', 'Digital Signature PDF')], default='system', max_length=20)),
                ('audit_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='workflow_app.approvalcategory')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('approver_role', models.CharField(choices=[('maker', 'Maker'), ('checker', 'Checker'), ('branch_approval', 'Branch Approval'), ('head_office', 'Head Office'), ('cfo', 'CFO'), ('ceo', 'CEO'), ('board', 'Board'), ('compliance', 'Compliance Officer'), ('legal', 'Legal Advisor'), ('custom', 'Custom Role')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('skipped', 'Skipped'), ('delegated', 'Delegated')], default='pending', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='step_attachments/')),
                ('action_taken_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('acting_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acting_approval_steps', to=settings.AUTH_USER_MODEL)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_steps', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow_app.approvalrequest')),
            ],
            options={
                'db_table': 'workflow_steps',
                'ordering': ['step_number'],
                'unique_together': {('request', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Request Created'), ('submitted', 'Submitted for Approval'), ('approved_step', 'Step Approved'), ('rejected_step', 'Step Rejected'), ('returned_step', 'Returned for Modification'), ('fully_approved', 'Fully Approved'), ('rejected', 'Request Rejected'), ('returned', 'Returned to Initiator'), ('resubmitted', 'Resubmitted'), ('payment_initiated', 'Payment Initiated'), ('payment_released', 'Payment Released'), ('email_sent', 'Email Notification Sent'), ('delegated', 'Approval Delegated'), ('commented', 'Comment Added'), ('pdf_generated', 'PDF Generated'), ('approver_added', 'Approver Added Dynamically'), ('approver_removed', 'Approver Removed')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workflow_app.approvalrequest')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='workflow_app.approvalstep')),
            ],
            options={
                'db_table': 'workflow_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Branches',
                'db_table': 'workflow_branches',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='workflow_app.branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='workflow_app.branch'),
        ),
        migrations.CreateModel(
            name='DelegationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegated_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField()),
                ('authority_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('acting_approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegation_logs_as_acting', to=settings.AUTH_USER_MODEL)),
                ('original_approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegation_logs_as_original', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_delegation_logs',
                'ordering': ['-delegated_at'],
            },
        ),
        migrations.CreateModel(
            name='DigitalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('signature_hash', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_signature', to='workflow_app.approvalstep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_digital_signatures',
            },
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='workflow_app.division'),
        ),
        migrations.AddField(
            model_name='approvalcategory',
            name='required_division',
            field=models.ForeignKey(blank=True, help_text='At least N approvers must be from this division', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow_app.division'),
        ),
        migrations.AddField(
            model_name='user',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='workflow_app.division'),
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'On Leave'), ('ended', 'Leave Ended')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_leaves',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('approval_required', 'Approval Required'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('returned', 'Returned for Correction'), ('completed', 'Workflow Completed'), ('comment', 'Comment Added'), ('payment', 'Payment Update'), ('info', 'Information')], default='info', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workflow_app.approvalrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('full', 'Full Payment'), ('partial', 'Partial Payment (Installments)')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('number_of_installments', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('released', 'Released'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiated_payments', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='workflow_app.approvalrequest')),
            ],
            options={
                'db_table': 'workflow_payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('released', 'Released')], default='pending', max_length=20)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='workflow_app.payment')),
            ],
            options={
                'db_table': 'workflow_installments',
                'ordering': ['installment_number'],
            },
        ),
        migrations.CreateModel(
            name='RequestVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status_snapshot', models.CharField(max_length=20)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='workflow_app.approvalrequest')),
                ('saved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_request_versions',
                'ordering': ['version_number'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='workflow_app.approvalcategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflow_templates',
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplateStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('approver_role', models.CharField(choices=[('maker', 'Maker'), ('checker', 'Checker'), ('branch_approval', 'Branch Approval'), ('head_office', 'Head Office'), ('cfo', 'CFO'), ('ceo', 'CEO'), ('board', 'Board'), ('compliance', 'Compliance Officer'), ('legal', 'Legal Advisor'), ('custom', 'Custom Role')], max_length=30)),
                ('role_label', models.CharField(blank=True, max_length=100)),
                ('default_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_steps', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow_app.workflowtemplate')),
            ],
            options={
                'db_table': 'workflow_template_steps',
                'ordering': ['step_number'],
                'unique_together': {('template', 'step_number')},
            },
        ),
    ]
